### ISSUE TITLE
java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by etwatson** [mozack/abra#12]
Greetings!  I am encountering a java error when running abra. I thought the problem was that my regions are too small (smaller than kmer). I have a de novo genome, and I am interested in coding indels, so my regions file is a CDS.bed file and my gene prediction software produced some impossibly small genes. However, a larger CDS also produces the same error. 

Here is my command:
```bash
java -Xmx34g -jar abra-0.82.jar --in SC_049.srt.RG.bam --ref genome_v3.fasta --out SC_049.abra.bam --working abra/ --targets CDS.bed
```
It crashes on the first scaffold following a particular region, scaffold_252_213187_213194:
```
Assembling: -> abra//scaffold_252_68589_69038_contigs.fasta_k13
Done assembling(0): abra//scaffold_252_68389_68789_contigs.fasta_k13, 24
Elapsed_msecs_in_NativeAssembler	Region:	scaffold_252_68389_68789	Length:	400	ReadCount:	334	Elapsed	73	Assembled	true
Mon Sep 29 11:15:44 PDT 2014 : Processing region: scaffold_252_213187_213194
java.lang.NegativeArraySizeException
	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:64)
	at java.lang.StringBuffer.<init>(StringBuffer.java:108)
	at abra.CompareToReference2.getSequence(CompareToReference2.java:392)
	at abra.KmerSizeEvaluator.getBases(KmerSizeEvaluator.java:44)
	at abra.KmerSizeEvaluator.identifyMinKmer(KmerSizeEvaluator.java:97)
	at abra.NativeAssembler.assembleContigs(NativeAssembler.java:140)
	at abra.ReAligner.processRegion(ReAligner.java:691)
	at abra.ReAlignerRunnable.go(ReAlignerRunnable.java:21)
	at abra.AbraRunnable.run(AbraRunnable.java:19)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NegativeArraySizeException
	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:64)
	at java.lang.StringBuffer.<init>(StringBuffer.java:108)
	at abra.CompareToReference2.getSequence(CompareToReference2.java:392)
	at abra.KmerSizeEvaluator.getBases(KmerSizeEvaluator.java:44)
	at abra.KmerSizeEvaluator.identifyMinKmer(KmerSizeEvaluator.java:97)
	at abra.NativeAssembler.assembleContigs(NativeAssembler.java:140)
	at abra.ReAligner.processRegion(ReAligner.java:691)
	at abra.ReAlignerRunnable.go(ReAlignerRunnable.java:21)
	at abra.AbraRunnable.run(AbraRunnable.java:19)
	at java.lang.Thread.run(Thread.java:745)
Num reads: 360
Num nodes: 1039
Remaining nodes after pruning step 1: 756
Remaining nodes after pruning step 2: 754
num root nodes: 2
Done assembling(0): abra//scaffold_252_60836_61423_contigs.fasta_k15, 144
Done assembling(0): abra//scaffold_252_68589_69038_contigs.fasta_k13, 289
```
Having a look at this region, it is smaller than the kmer and likely not real:
scaffold_252_213187_213194

However, I get the same error with a larger region (although still very small): scaffold_252_221019_221342

**Comment by mozack** [comment]
Added additional target region validation on startup to hopefully generate more meaningful error messages.
