### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by dbrawand** [mozack/abra#16]
Hi,
I get this error on some of our computation nodes but can't figure out what is going wrong/ is different.
```bash
/share/java/jdk1.7.0/bin/java -Xmx4g -jar abra-0.92-SNAPSHOT-jar-with-dependencies.jar --in da82e52f.bam --out da82e52f.realigned.unsorted.bam --ref human_g1k_v37.fasta --bwa-ref human_g1k_v37.fasta --threads 4 --targets final_baitcapture_moderate_1_Regions.bed --working /tmp/tmp_5d98 --mad 250 --mapq 10 --mer 0.1 --mur 500000 --rcf 0.01 
```
> Exception in thread "main" java.lang.UnsatisfiedLinkError: > /tmp/tmp_5d98/libAbra.so: /tmp/tmp_5d98/libAbra.so: undefined symbol: _ZZN6google11sparsegroupIPKcLt48ENS_27libc_allocator_with_reallocIS2_EEE12bits_in_charEhE7bits_in
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1928)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1825)
        at java.lang.Runtime.load0(Runtime.java:792)
        at java.lang.System.load(System.java:1059)
        at abra.NativeLibraryLoader.load(NativeLibraryLoader.java:45)
        at abra.ReAligner.init(ReAligner.java:1093)
        at abra.ReAligner.reAlign(ReAligner.java:116)
        at abra.ReAligner.run(ReAligner.java:1214)
        at abra.Abra.main(Abra.java:12)

I tried Java 1.7.0 and 1.8.0 with the same outcome.

Thanks for your help

**Comment by dbrawand** [comment]
This error occurred using your prebuilt jar. Building it from source solved the problem so far.

**Comment by mozack** [comment]
OK.  Let me know if you run into any further trouble.
