### ISSUE TITLE
 [fwrite] Remote I/O error

### ISSUE THREAD

**Issue by bcantarel** [mozack/abra#24]
I am running Abra-0.96 using abra-0.96-SNAPSHOT-jar-with-dependencies.jar

It runs over 24 hours and gives me the following error:

Clock time in Align and clean contigs: 49461
Sat Dec 19 21:10:43 CST 2015 : Indexing contigs
Running: [bwa index -a bwtsw /qbrc/home/bcantarel/scratch/abra_temp_S2/clean_contigs.fasta]
[bwa_index] Pack FASTA... [fwrite] Remote I/O error
Stream thread done.
Stream thread done.
BWA time: 1313 seconds.
Exception in thread "main" java.lang.RuntimeException: BWA exited with non-zero return code : [1] for command: [bwa index -a bwtsw /qbrc/home/bcantarel/scratch/abra_temp_S2/clean_contigs.fasta]
	at abra.Aligner.runCommand(Aligner.java:76)
	at abra.Aligner.runCommand(Aligner.java:33)
	at abra.Aligner.index(Aligner.java:103)
	at abra.ReAligner.alignReads(ReAligner.java:396)
	at abra.ReAligner.reAlign(ReAligner.java:214)
	at abra.ReAligner.run(ReAligner.java:1240)
	at abra.Abra.main(Abra.java:12)

When I try to run this command directly, I have the error:
[bwa_index] unknown algorithm: 'bwtsq'.

Is there a way for me to run the indexing and not have abra start over at the beginning?  Also looks like this indexing command is from a previous bwa version, is it possible to update?  I couldn't compile on my system, hence I am using the precompiled version.

**Comment by mozack** [comment]
BWA is not compiled into ABRA.  Rather, it uses the version that is in your command PATH.  What version do you have in your path?

**Comment by bcantarel** [comment]
Oh, I see, there is a "global" install of 0.7.9 but I use a local install -- of  0.7.12  --
I guess my comment want that the command bwa index -a bwtsw does not work for all versions of bwa...  
Also, I wanted to know if there is a way for me to run the indexing continue with the rest of the steps and not have abra start over at the beginning?

**Comment by mozack** [comment]
Sorry, I don't currently have a way to do that - short of modifying the code.  That is an unusually long run time.  Can you provide a line count of the index?

In the working dir run:  wc -l clean_contigs.fasta

**Comment by bcantarel** [comment]
255611210

**Comment by mozack** [comment]
That is too many contigs and is unlikely to complete with the supported BWA version.

I suggest retrying with more aggressive graph pruning.  i.e.

`--mnf 5 --mbq 150`
