### ISSUE TITLE
Exception in thread Error

### ISSUE THREAD

**Issue by tinuthomas** [mozack/abra#26]
ABRA version - 0.96
Platform - CentOS
command used to run ABRA
`java -Xmx4G -jar abra-0.96-SNAPSHOT-jar-with-dependencies.jar --in C26.bam --out C26.ABRA.bam --ref hs37d5.fa --targets Agilent_Nimblegen.bed  --threads 4 --working temp_dir >abra.log 2> abra.error`

**abra.error**
```### 
Loading reference map:  hs37d5.fa
        Chromosome: 1 length: 249250621
        Chromosome: 2 length: 243199373
        Chromosome: 3 length: 198022430
        Chromosome: 4 length: 191154276
        Chromosome: 5 length: 180915260
        Chromosome: 6 length: 171115067
        Chromosome: 7 length: 159138663
        Chromosome: 8 length: 146364022
        Chromosome: 9 length: 141213431
        .....
        Chromosome: GL000224.1 length: 179693
        Chromosome: GL000223.1 length: 180455
        Chromosome: GL000195.1 length: 182896
        Chromosome: GL000212.1 length: 186858
        Chromosome: GL000222.1 length: 186861
        Chromosome: GL000200.1 length: 187035
        Chromosome: GL000193.1 length: 189789
        Chromosome: GL000194.1 length: 191469
        Chromosome: GL000225.1 length: 211173
        Chromosome: GL000192.1 length: 547496
        Chromosome: NC_007605 length: 171823
        Chromosome: hs37d5 length: 35477943
Done loading ref map.  Elapsed secs: 169
**Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1**
        at abra.RegionLoader.load(RegionLoader.java:45)
        at abra.ReAligner.getRegions(ReAligner.java:702)
        at abra.ReAligner.loadRegions(ReAligner.java:712)
        at abra.ReAligner.reAlign(ReAligner.java:132)
        at abra.ReAligner.run(ReAligner.java:1240)
        at abra.Abra.main(Abra.java:12)
```

abra.log

```
Starting 0.96 ...
input0: C26.bam
output0: C26.ABRA.bam
regions: Agilent_Nimblegen.bed
reference: hs37d5.fa
bwa index: hs37d5.fa
working dir: temp_dir
num threads: 4
max unaligned reads: 50000000
minEdgeFrequency: 0
minNodeFrequncy: 2
minContigLength: -1
maxPotentialContigs: 5000
minBaseQuality: 60
minReadCandidateFraction: 0.01
maxAverageRegionDepth: 250
minEdgeRatio: 0.02

rna: null
rna output: null
paired end: true
use intermediate bam: false
Java version: 1.7.0_85
hostname: nski0244
Loading native library from: /opt/ngstools/aligners/temp_dir/libAbra.so
Fri May 13 15:29:40 EDT 2016 : Reading Input SAM Header and identifying read length
Fri May 13 15:29:40 EDT 2016 : Identifying header and determining read length
Min insert length: 0
Max insert length: 246703503
Fri May 13 15:31:41 EDT 2016 : Max read length is: 93
Fri May 13 15:31:41 EDT 2016 : Min contig length: 94
Fri May 13 15:31:41 EDT 2016 : Read length: 93
Fri May 13 15:31:41 EDT 2016 : Loading target regions

```

Would appreciate help,

Thank you

**Comment by mozack** [comment]
Could you please post or send me your Agilent_Nimblegen.bed file?

**Comment by mozack** [comment]
lmose at unc dot edu
