### ISSUE TITLE
Abra error

### ISSUE THREAD

**Issue by yuhongning** [mozack/abra#36]
Hi,
I am trying this tool to do realignment in a few regions, but got following error: 
java.lang.NegativeArraySizeException
        at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:64)
        at java.lang.StringBuffer.<init>(StringBuffer.java:108)
        at abra.CompareToReference2.getSequence(CompareToReference2.java:400)
        at abra.KmerSizeEvaluator.getBases(KmerSizeEvaluator.java:44)
        at abra.KmerSizeEvaluator.identifyMinKmer(KmerSizeEvaluator.java:98)
        at abra.NativeAssembler.assembleContigs(NativeAssembler.java:273)
        at abra.ReAligner.processRegion(ReAligner.java:592)
        at abra.ReAlignerRunnable.go(ReAlignerRunnable.java:21)
        at abra.AbraRunnable.run(AbraRunnable.java:20)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)

My commandline is: java -Xmx8G -jar $ABRA --in ${inbam} --out ${outbam} --ref ${hg19} --targets ${bed} --working ~/abra/ > abra.log
Screen shots of errors  and target bed file are attached. I really appreciate if you could point me possible reasons.
Thanks,
Yuhong

![abra_test_error](https://user-images.githubusercontent.com/18533709/27613718-00d2fe38-5b52-11e7-88f5-cb8dcae60693.png)

**Comment by mozack** [comment]
Could you please email your complete log file and bed file to lmose at unc dot edu ?

**Comment by yuhongning** [comment]
I just sent you the complete log file and bed file. Please let me know if additional information is needed. Thanks a lot!
